name: Create Jira issue
on:
  issues:
    types: 
      - opened
jobs:
  create-issue:
    name: Create Jira issue
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}

      - name: Checkout main code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Issue Parser
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/issue_form.yml

      - name: Log Issue Parser
        run: |
          echo '${{ steps.issue-parser.outputs.jsonString }}'

      - name: Convert markdown to Jira Syntax
        uses: peter-evans/jira2md@v1
        id: md2jira
        with:
          input-text: |
            ### Github Issue Link
            - ${{ github.event.issue.html_url }}

            ${{ github.event.issue.body }}
          mode: md2jira

      - name: Create Issue
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: KAN
          issuetype: 기능
          summary: "${{ github.event.issue.title }}"
          description: "${{ steps.md2jira.outputs.output-text }}"
          fields: |
            {
              "parent": {
                "key": "${{ steps.issue-parser.outputs.issueparser_parentKey }}"
              }
            }

      - name: Log created issue
        run: echo "Jira Issue ${{ steps.issue-parser.outputs.parentKey }}/${{ steps.create.outputs.issue }} was created"

      - name: Checkout develop code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Create branch with Ticket number
        run: |
          # 1️⃣ GitHub 이슈 제목 가져오기
          ISSUE_TITLE="${{ github.event.issue.title }}"
          echo "Original Issue Title: $ISSUE_TITLE"

          # 2️⃣ 공백을 '-'로 변경, 특수 문자 제거 (한글 포함)
          SAFE_TITLE=$(echo "$ISSUE_TITLE" | sed 's/ /-/g' | tr -cd '[:alnum:]-ㄱ-ㅎㅏ-ㅣ가-힣')
          echo "Sanitized Issue Title: $SAFE_TITLE"

          # 3️⃣ 제목이 비어있으면 기본값 사용
          if [ -z "$SAFE_TITLE" ]; then
            SAFE_TITLE="new-issue"
          fi

          # 4️⃣ 브랜치 이름 UTF-8 인코딩 처리 (한글 지원)
          BRANCH_NAME="${{ steps.create.outputs.issue }}-${SAFE_TITLE}"
          echo "Final Branch Name: $BRANCH_NAME"

          # 5️⃣ 한글 브랜치 checkout을 위한 설정 (Git이 한글을 인식하도록 환경 설정)
          git config --global core.quotepath false
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"

      - name: Update issue title
        uses: actions-cool/issues-helper@v3
        with:
          actions: "update-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "${{ steps.create.outputs.issue }} ${{ github.event.issue.title }}"
